services:
  rtmp:
    build: .
    ports:
      - 1935:1935
      - 80:80
    networks:
      - rtmp-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./tmp/hls:/tmp/hls
      - ./var/log:/var/log/nginx
  websockify:
    build:
      context: .
      dockerfile: webscokify.Dockerfile
    ports:
      - 9001:9001
    networks:
      - rtmp-network
    depends_on:
      - rtmp
networks:
  rtmp-network:
    # Specify driver options
    driver: bridge